background {
    monitor =
    path = /home/paul/code/nixos-config/wallpapers/01-cwb.jpg
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 300, 60
    position = 0, 0
    halign = center
    valign = center
    outline_thickness = 2
    rounding = 0
    dots_center = true
    fade_on_empty = false
    placeholder_text = <span foreground="##B8B5AC">Password...</span>
    font_color = rgb(B8B5AC)
    inner_color = rgb(0B0E14)
    outer_color = rgb(FF8F40)
    check_color = rgb(E6C54C)
    fail_color = rgb(F07178)
    shadow_passes = 2
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%I:%M')"
    color = rgba(FF8F40, 1.0)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}
