add_newline = true

format = """[](#151019)$os$username[](bg:#8a7aa6 fg:#151019)$directory[](fg:#8a7aa6 bg:#1e1824)$git_branch$git_status[](fg:#1e1824 bg:#151019)$nodejs$python$rust$golang$nix_shell[](fg:#151019)$fill$cmd_duration$status$jobs$time$line_break$character"""

[os]
disabled = false
style = "bg:#151019 fg:#c2b6c0"

[os.symbols]
Macos = ""

[username]
show_always = true
style_user = "bg:#151019 fg:#bf7593"
style_root = "bg:#151019 fg:#c0667e"
format = "[ $user ]($style)"

[directory]
style = "fg:#060406 bg:#8a7aa6"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
symbol = ""
style = "bg:#1e1824 fg:#bf7593"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#1e1824 fg:#c0667e"
format = "[$all_status$ahead_behind ]($style)"

[nodejs]
symbol = ""
style = "bg:#151019 fg:#82a08c"
format = "[ $symbol ($version) ]($style)"

[python]
symbol = ""
style = "bg:#151019 fg:#c4a878"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = ""
style = "bg:#151019 fg:#b07e90"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = ""
style = "bg:#151019 fg:#8c8aa6"
format = "[ $symbol ($version) ]($style)"

[nix_shell]
symbol = ""
style = "bg:#151019 fg:#8a7aa6"
format = "[ $symbol $state ]($style)"

[fill]
symbol = " "

[cmd_duration]
min_time = 500
style = "fg:#c4a878"
format = "[  $duration ]($style)"

[status]
disabled = false
style = "fg:#c0667e"
symbol = "✖ "
format = "[ $symbol$status ]($style)"
map_symbol = true

[jobs]
symbol = " "
style = "fg:#b07e90"
number_threshold = 1
format = "[ $symbol$number ]($style)"

[time]
disabled = false
time_format = "%H:%M"
style = "fg:#948a98"
format = "[ $time ]($style)"

[character]
success_symbol = "[❯](bold #82a08c)"
error_symbol = "[❯](bold #c0667e)"
vimcmd_symbol = "[❮](bold #bf7593)"
